### ISSUE TITLE
faculty with two affiliations

### ISSUE THREAD

**Issue by adam-morrison** [emeryberger/CSrankings#130]
How should faculty with two affiliations be handled?

Commit 8e710a63 removed duplicated affiliations of some faculty.  Some of them, however, _are_ affiliated with two institutions, spending time in both and specifying them as their affiliations in papers:
- Ran Canetti (e.g., https://eprint.iacr.org/2014/243.pdf)
- Kyle Jamieson (e.g., http://dl.acm.org/citation.cfm?id=2906417)
- Nassir Navab (e.g., https://www.ncbi.nlm.nih.gov/pubmed/26984551)
- Ronitt Rubinfeld (e.g., http://www.jmlr.org/proceedings/papers/v49/aliakbarpour16.pdf)
- Nir Shavit (e.g., http://dl.acm.org/citation.cfm?id=2935825)

**Comment by emeryberger** [comment]
Tricky issue. The current criterion is that faculty inclusion is based on full-time tenure-track status at a particular campus...

**Comment by adam-morrison** [comment]
AFAIK they are tenure-track (some tenured, in fact) in both institutions.  The folks I know alternate spending periods (e.g., a year) full-time at each campus, but modifying the rankings each time they move seems awkward...

**Comment by emeryberger** [comment]
Indeed. Tell them to stay put! Seriously, though, incorporating fractional weighting is not necessarily a great idea, but it may be the only alternative if faculty legitimately are full-time employed on an alternating basis by multiple institutions.

**Comment by adam-morrison** [comment]
Something like [this](https://github.com/adam-morrison/CSrankings/commit/e53ed74a9316996fe0c1c99b283e064abc030648)?  Would you consider merging it?

BTW, when testing this code I found that Aggelos Kiayias is listed twice and it seems that the University of Edinburgh is the correct affiliation.

**Comment by scherbaum** [comment]
Not exactly the same topic, but closely related:

There is quite a few faculty members with two affiliations, but both located on the same campus. 
For example: Faculty members being affiliated with an institute (A) and a university (B), both on the same campus. Currently, those faculty members need to decide whether to be listed as a member of A or B. Allowing two affiliations would solve this issue. However, I absolutely understand that adding a second affiliation may be tricky. 

**So what about the following approach:** 
- You could allow to *additionally* rank by campus location
- Faculty members would as usual enter a primary affiliation
- As each affiliation comes with a physical campus location / city / address though, you could allow users to rank by location / venue too (clustering by, e.g., zip code, city name or similar, to be defined)
- if affiliations come with multiple venues, than the faculty member should choose one (one location policy)

**This would least** 
1. solve the issue at least for quite a few two-affiliation faculty members
2. and as a positive side effect add a nice new feature for everybody else using the CSranking: It would allow users to figure which *venue* concentrates the most excellent CS researchers on a campus (=location) at a glance, which currently is quite tricky to extract (due to the one affiliation policy)
