### ISSUE TITLE
Add CCC to the Algorithms and Complexity box?

### ISSUE THREAD

**Issue by grigory** [emeryberger/CSrankings#1904]
Dear CSrankings team,

CCC is the top conference in complexity (the counterpart of SODA for algorithms).

I was wondering if it might be possible to add it to the "Algorithms and Complexity" box on CSrankings?

Thanks!

--
Best regards,
Grigory Yaroslavtsev,
Assistant Professor of Computer Science,
Director for the Center for Algorithms and Machine Learning,
Indiana University, Bloomington,
http://grigory.us

**Comment by jgrochow** [comment]
100% agree. Having SODA but not CCC reflects a bias towards algorithms over complexity. This bias is perhaps one that is present in the world (indeed, SODA is much bigger than CCC - though that presumably reflects other things like number of applications, etc.), but from the perspective of ranking departments based on theory groups, omitting contributions to complexity theory that are in the top specialist conference seems...absurd?

**Comment by jalman** [comment]
I agree as well. Since the box is called "Algorithms and Complexity", it's strange to not include the top Complexity conference.

**Comment by jgrochow** [comment]
I'd like to reopen this issue. Looks like it got auto-closed due to lack of activity, but seems to me like this is very much still an open issue that I and many others would like to see resolved (or at least get a response about).

**Comment by jakobnordstrom** [comment]
Yes, I think it seems clear to most people active in computational complexity theory that the flagship conference for this research area should be included. STOC and FOCS cover both algorithms and complexity theory, as well as many other areas of theoretical computer science. In addition to that, SODA seems to be for algorithms what CCC is for complexity theory. But I wonder if lobbying efforts should also be directed towards the team behind the CORE ranking http://portal.core.edu.au/conf-ranks/ --- maybe the problem is that SODA gets an A*-ranking there whereas CCC is only A-ranked. Looking that the very wide range of A-conferences in CORE, which extends all the way to, e.g., APPROX, RANDOM, and ESA, it seems pretty obvious that the ranking for CCC is just off there...

**Comment by jgrochow** [comment]
@jakobnordstrom I looked at the description of the CORE rankings, and I think actually the one criteria there which perhaps sets apart A* conferences from A conferences which could legitimately explain the difference in CORE ranking between SODA and CCC is the part about "visibility outside the immediate subfield". I feel like SODA is probably better well-known to non-theorists (again, because of the applications to other areas), although CCC is still very highly regarded within the Theory community. So I think a challenge to the CORE rankings would be unlikely to change things. 

That said, I still think if you are ranking departments based on a box called "Algorithms & *Complexity*" it should really include the top specialist conference *in complexity*.

It was great that surveys were done of recent PCs from top conferences in areas to figure out which other conferences to include; but Theory does not appear in the survey results :( (was it surveyed?).
