### ISSUE TITLE
Break MPI into constituent organizations

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/CSrankings#2099]
MPI is not a single entity, but rather a collection on different campuses (in different cities and even countries); for consistency and to avoid confusion, these need to be broken out into different institutions. Break out into MPI-IS (https://en.wikipedia.org/wiki/Max_Planck_Institute_for_Intelligent_Systems), MPI-SS (https://en.wikipedia.org/wiki/Max_Planck_Institute_for_Software_Systems) and MPI-INF (https://en.wikipedia.org/wiki/Max_Planck_Institute_for_Informatics).

**Comment by emeryberger** [comment]
Completed with https://github.com/emeryberger/CSrankings/commit/3df01f715f65cc6d73ee618441e02b90ec53c2db.

**Comment by Shreyas4991** [comment]
Greetings, 
I recently came across [tweets](https://twitter.com/lhochstein/status/1201216628735627264?s=19) regarding the utility of csrankings.org, for grad school applicants, that you had replied to.

While splitting MPI into its constituent organisations seems appropriate, I believe it might be useful to grad applicants, to add an entry for [Saarland Informatics Campus](https://saarland-informatics-campus.de/en/forschung-research/#researchinstitutes_en) as a whole, because these institutes are right next to each other, and offer multiple graduate programmes together including [Saarbrücken graduate school](https://www.graduateschool-computerscience.de/), the [cs@maxplanck programme](https://www.cis.mpg.de/graduate-programs/), and the  [imprs-cs programme](https://www.imprs-cs.de/). 

Also, MPI INF and MPI SWS are in fact located to next to each other in the Saarland Informatics Campus at Saarbrücken (although MPI SWS has another campus at Kaiserlautern)
