### ISSUE TITLE
add NDSS to computer security

### ISSUE THREAD

**Issue by zhhailon** [emeryberger/CSrankings#263]
NDSS is often regarded as one of the top-tier security conferences, along with Oakland, CCS and USENIX Security.

**Comment by emidec** [comment]
I think the point is that all communities have at most 3 conferences. I'm not entirely sure how to argue how to choose 3 out of the top 4 and I'm pretty sure everyone has different opinions. 

IMHO it's actually quite hard to compare -- e.g., CCS is much bigger (multiple tracks) than, e.g., NDSS (mostly single track) and S&P has started much earlier than the others. 
If one were to pick a purely quantitative metric, then I guess h5-index or h5-median are what we can easily look at -- see https://scholar.google.co.uk/citations?view_op=top_venues&hl=en&vq=eng_computersecuritycryptography.

With the former, then the current selection is correct, with the latter NDSS is clearly the "winner" over Usenix.

Thoughts?

**Comment by weikengchen** [comment]
[Deleted]

**Comment by tosanjay** [comment]
I too think that NDSS should be included. As mentioned by @weikengchen, CCS has larger scope, thus more papers. In the recent past, it was even told that one 'C' in CCS is crypto and in this ranking, we do have a separate field for crypto conferences.

**Comment by weikengchen** [comment]
@tosanjay  The problem is that according to the computer-generated ranking (Google Ranking @emidec mentioned), it is hard to pick NDSS and remove CCS. 

I think h5-index and h5-median is not a good metric. Because they reflect the top papers, not the average papers (so not good for ranking the professors). And CCS increases the size just in the recent years, there are many solid works every year because many professors still submit their best works, too.

I would prefer to observe for another year or two years. Internet Society is building an independent website for NDSS. If they become increasingly serious about the conference, I hope they make progress.

I think another thing is that Google should consider a citation record that only considers citations from good/reasonable conferences -- for example, CCS cites CCS counts, a random conference or small journal cites XXX does not count.

**Comment by emidec** [comment]
I think the consideration is to have 4 conferences rather than having to drop one. But if we go for the h index then Usenix needs to be dropped.

**Comment by weikengchen** [comment]
@emeryberger said he prefers that no area has more than 3 top conferences. I agree with you. For example, many China scholars refer "BIG 4 SEC CONF" as S&P, SEC, CCS, NDSS, for more than 10 years. This would be a fair choice. 

Two solutions:
1. we can start bugging @emeryberger for an exception.
2. we can separate the computer security to more than one area, similar to AI? I mean, Computer Security = S&P and SEC, Network Security = CCS and NDSS, though such a classification is not obvious.

**Comment by tosanjay** [comment]
I would prefer too that we keep CCS as it IS a top conference, but NDSS should be there (-> we should request @emeryberger to create an exception as NDSS is equally competitive. see http://faculty.cs.tamu.edu/guofei/sec_conf_stat.htm).

**Comment by emeryberger** [comment]
Just so everyone knows, I am working on this issue.

**Comment by impedimentToProgress** [comment]
Crazy counter-proposal: From reading the comments, it seems that there is no debate that Oakland and USENIX are the top two security conferences.  Given that, how about just listing those two security conferences.  Add a third when there is a clear "winner" between CCS and NDSS.

**Comment by weikengchen** [comment]
This kills too many papers @impedimentToProgress.

Because CCS was definitely top-tier first-class several years ago. How about splitting the CCS according to time?

**Comment by tosanjay** [comment]
@impedimentToProgress : I think we are requesting to keep both- NDSS and CCS.

**Comment by tosanjay** [comment]
BTW, latest CORE2018 ranking of conferences puts NDSS at A* level.

**Comment by andrewcmyers** [comment]
I think NDSS has improved, but I don't see any diminution of the quality of CCS. CCS has a broader scope in practice, being more congenial to papers on crypto and formal security. It also gets more submissions than the other conferences. So it is not surprising that it publishes more papers. I would definitely keep it on the list.

**Comment by msirivia** [comment]
I feel the only solution to this problem is to have a varying number of conferences per area.

The number of top tier conferences depends on the activitity in the area and the number of papers per conference.

Not all areas are the same and by treating them equally we are bound to make mistakes.

Take for example Measurements. It has only two conferences, and rightly so.

IMHO, NDSS should be listed above the fold as I think Security has indeed  4 top tier conferences.

Of course I respect Emery's survey process. Just my 2 cents in case the obstacle here is the limit of 3 conferences.

**Comment by fycus-tree** [comment]
@msirivia Any thoughts on the automated process in #859 ?

**Comment by msirivia** [comment]
This is a great direction. I think it would be valuable as a metrics-based alternative to this ranking.

Perhaps this ranking should stick to using survey-selected top tier conferences as quality proxy.

**Comment by impedimentToProgress** [comment]
Anyone know the volume of submissions to NDSS this year?  I am interested to see if Oakland changing their deadline model has impacted NDSS; it seemed to hurt NDSS last year (but, you need at least two points to make a line...).

**Comment by weikengchen** [comment]
I think not likely for the following two reasons.
(1) If someone has a rejected paper from CCS, but the paper can be improved to the quality of acceptance in CCS. This paper would be likely submitted to Oakland or next year's USENIX Security.
(2) If someone has a rejected paper from CCS, and this paper is not likely to be improved to the quality of acceptance in CCS, such paper is not likely to be submitted to Oakland due to the end-of-year rise of difficulty, and NDSS would be a good try.

**Comment by impedimentToProgress** [comment]
@weikengchen What's this "end-of-year rise of difficulty" you speak of?

**Comment by weikengchen** [comment]
@impedimentToProgress Many people procrastinate in Oakland, causing the quality of submitted papers better. Since once rejected, a paper cannot be submitted in one year, people would be willing to delay one month's submission for more benchmark, for better construction. At the end of the year, many heavily polished and repeatedly discussed papers are submitted.

**Comment by impedimentToProgress** [comment]
Take a look at the odds of getting a positive decision per month (as a surrogate for paper quality):

https://www.ieee-security.org/TC/SP2018/submissions.html
https://www.ieee-security.org/TC/SP2019/submissions.html

It suggests that papers submitted in the last few months of last year were of similar quality.

Comparing this year with last, it is clear any trends that once existed are changing.  My experience as a PC member (with the small sample size of papers that I have seen) matches the global trend in those numbers.

**Comment by weikengchen** [comment]
@impedimentToProgress Thanks for the information from a PC member. Then I have a question, is "getting a positive decision per month" a roughly preconfigured parameter or an unsupervised result?

**Comment by impedimentToProgress** [comment]
@weikengchen Unsupervised; hence a surrogate for paper quality.

**Comment by weikengchen** [comment]
Then the "end-of-year rise" makes no sense. I deleted my misleading claim.

**Comment by emidec** [comment]
NDSS received 518 valid submissions this year. Record high number, up from 331 last year and ~420 two years ago

**Comment by impedimentToProgress** [comment]
@emidec  Interesting.  For reference, the number of papers submitted in August (first post-CCS-response submission opportunity) to Oakland was almost double previous months.

**Comment by gannimo** [comment]
As the upcoming PC Chair for NDSS (for 2023 and 2024), I would like to revisit this issue and reopen the discussion.
Even according to the survey @emeryberger did ( https://github.com/emeryberger/CSrankings/blob/gh-pages/docs/CSrankings%20survey%20results.pdf ) NDSS is clearly among the top tier conferences.

The security community univocally refers to the security conferences as the "top 4": https://www.s3.eurecom.fr/~balzarot/notes/top4_2020/ or https://nebelwelt.net/pubstats/top-authors-sys_sec.html

If we would like to distinguish, Oakland has been around for the longest and CCS provides a much broader view (i.e., CCS could similarly be (co-)listed in Crypto or Verification). NDSS and Usenix (as mentioned in this thread) are the two systems focused conferences.

As mentioned earlier, if we must enforce a hard cap, we could split this into "Security" with CCS and Oakland and "Applied Security" for Usenix and NDSS. The best option IMO is though to include NDSS among the 4 security conferences to correspond to the de-facto state in security.

I would like to hear what the continued arguments are to NOT include NDSS in CSRankings (by default) and what is necessary to change it!
