### ISSUE TITLE
3rd conference for Web and Information Retrieval?

### ISSUE THREAD

**Issue by emidec** [emeryberger/CSrankings#2667]
Hi there,

There are only two venues in the Web & Information retrieval category: WWW and SIGIR, while most categories have three.

I would propose running a survey to add either ICWSM ((http://dblp.uni-trier.de/db/conf/icwsm/index.html)) of WSDM (https://dblp.org/db/conf/wsdm/).

Personally, I believe ICWSM is at least as strong a venue as SIGIR, and I believe a lot of the top researchers in this field agree with me. ICWSM is _the_ venue for computational social science and has grown even further in the past couple of years thanks to rolling deadlines and R&Rs.

Unfortunately, Google Scholar doesn't capture the right h5 values for it since it seems to report it twice, once as International Conference on Web and Social Media (ICWSM) and once as International AAAI Conference on Web and Social Media (see https://scholar.google.co.uk/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems) 

Thank you,
Emiliano

**Comment by gianlucasb** [comment]
I second this. I don't think that ICWSM is less competitive than SIGIR or WWW.

**Comment by elena-uic** [comment]
This issue has been raised multiple times since 2017 but all issues were closed (366, 427, 564) with what looks like no clear resolution. This is in no way a criticism of Emery Berger who is graciously providing the service of CSRankings. At this point it would be great to know what it would take for CSRankings to start including ICWSM and WSDM (and ICLR) and how we can help.

I don't think it should be an either-or between ICWSM and WSDM. It is true that adding both ICWSM and WSDM to Web & IR would increase the number of conferences to four but this is not the only possible solution. An alternative solution is to split the current DM & ML area into two separate areas DM (KDD) and ML (NeurIPS, ICML), a potential solution which Emery mentioned two years ago in a personal email exchange. Then WSDM can be added to DM, ICWSM to Web & IR, and [ICLR](https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_artificialintelligence) to ML, keeping the CSRankings tradition to have no more than 3 conferences per area. 

WSDM and ICWSM are two very competitive conferences, and including them in CSRankings under the general AI area would reflect the efforts of people who publish in them. WSDM is the second most prominent Data Mining conference after KDD, and ranks second in the [Data Mining & Analysis](https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_datamininganalysis) category of Google Scholar (excluding the journals). It has an acceptance rate of 16-18% and h5-median of 85 and these statistics are comparable to other conferences which are currently included under the general AI area, such as SIGIR (acceptance rate of 16-22% and h5-median of 81). ICWSM has similar statistics (acceptance rate of 13-17% and h5-median of 82) which may even be higher, as pointed out by Emiliano. 

Conference statistics change over time and their inclusion/exclusion in CSRankings likely has an impact on that. The first time I wrote to Emery Berger about this issue two years ago, AAAI, SIGIR and NAACL had much lower h5-median than both WSDM and ICWSM: SIGIR (h-median 66), AAAI (76), NAACL (79), WSDM (89), ICWSM (90). The conferences included in CSRankings have increased their h-medians significantly in the last two years while ICWSM and WSDM have not. It's hard to prove causality here but my guess is that the gap will only increase over time. That said, one can also make the argument that it's nice to keep WSDM and ICWSM on the smaller side for the sense of community they give, so not including them in CSRankings might be a good thing.
 
Note that I am not even trying to advocate for the other two well-known Data Mining conferences, ICDM and SDM (acceptance rate of 18-20% and h5-median of 49-55) though others may want to make a case for them too.

Thank you,
Elena Zheleva
