### ISSUE TITLE
Consider a third HPC venue

### ISSUE THREAD

**Issue by patrickb314** [emeryberger/CSrankings#41]
Candidates for a third are HPDC, SPAA, and probably ICS. There may not be an easy pick between these, so staying with just the current two (PPoPP and SC) may be the best option.

**Comment by ielhajj** [comment]
I think IPDPS (h5-index = 41) ranks higher than HPDC (h5-index = 29), ICS (h5-index = 29), and SPAA (h5-index = 25).

Other conferences with higher h5-index than HPDC, ICS, and SPAA include:
HPCA (h5-index = 42)
OOPSLA (h5-index = 36)
PPoPP (h5-index = 34)

All these conferences tend to have overlapping communities, so it seems unfair that HPDC and ICS make the cut but IPDPS, HPCA, OOPSLA, and PPoPP are dropped. Perhaps allowing for 4 venues per area instead of 3 would solve the problem. Because then you could do:

Computer architecture: ISCA, MICRO, ASPLOS, HPCA
Programming Languages: POPL, PLDI, OOPSLA, PPoPP
High-performance computing: SC, IPDPS, HPDC, ICS

**Comment by emeryberger** [comment]
As the FAQ explains, the conferences listed need to all be in roughly the same equivalence class. Comparing across areas is not meaningful.

**Comment by ielhajj** [comment]
That makes sense. That leaves just IPDPS which can be discussed in Issue #361. Thanks!
