### ISSUE TITLE
Consider adding a Distributed/Parallel Computing area

### ISSUE THREAD

**Issue by adam-morrison** [emeryberger/CSrankings#423]
Distributed/parallel computing touches theory, algorithms, systems and architecture.  Historically, the area's top conferences are co-sponsored by SIGACT, SIGOPS, SIGARCH, SIGPLAN and other societies. 
 Despite not having its own ACM SIG, distributed/parallel computing is recognized as a significant area that stands on its own.  For example, SIGACT and SIGOPS jointly sponsor a unique prize for this area, the Edsger W. Dijkstra Prize in Distributed Computing (http://www.podc.org/dijkstra).  The area is also very active and has a strong community.  For instance, even just two of the top conferences already have publications from more than 60 R1 institutions in the last 10 years (http://www.cs.tau.ac.il/~mad/R1-pubs-in-DC.html).

Since the primary audience of CSRankings is prospective graduate students, many of whom are interested in distributed/parallel computing, and (as shown above) the area is well-established, significant and active, we believe that adding it as an area in CSRankings would benefit the site and its users.

Mohsen Ghaffari and Adam Morrison

**Comment by adam-morrison** [comment]
Hi @emeryberger, do you happen to have any feedback on this?

**Comment by emeryberger** [comment]
Hi - thanks for the ping. I have actually spent considerable time talking about this with various people.

I assume you are arguing for SPAA and PODC as the top equivalence class in this area.

As you are probably aware, CSrankings is now essentially organized along ACM SIGs (which for historical reasons don't include major AI conferences, which are also included). This leaves this conferences that span conferences in a tricky spot unless one of the relevant SIGs considers it in their top equivalence class (as turns out to be the case for SIGARCH and ASPLOS). Creating a "new" area (outside the SIGs) is thorny, since it places me in the editorial position of deciding whole areas of CS (in effect), which is not a business I want to be in. Note that the inclusion criteria per numbers of pubs are actually focused on SIGs (some of which are excluded because they are not research-oriented, as measured by this definition).

I am sympathetic; I am well aware of the community and personally value its contributions but I do not see a clear way to adding new areas of CS that does not involve a pure editorial decision by myself (and which naturally could open the floodgates to other subareas of CS not covered by SIGs).

While the "easiest" solution from my perspective would be for your community to form its own SIG, this seems like a big ask. Perhaps the best approach would be for the various sponsoring SIGs to jointly provide a (signed) written request; this would put the decision squarely in the hands of the SIGs.

**Comment by marcniethammer** [comment]
Neither computer vision, natural language processing, cryptography, robotics, or visualization have ACM Sig backing. But they are included.  And I would argue strongly in favor of the inclusion of these areas.

Limiting inclusion of areas based on ACM Sigs or their written support seems artificial to me. Especially, since other areas frequently have their own associations (independent of an ACM Sig) that serve the same purpose. Creating an ACM Sig in such cases would essentially replicate what is already existing. I am not sure this is the case for distributed/parallel computing, but it is the case in other areas (see e.g., #611).

Since the objective is to rank CS departments, it would make sense, in my opinion, to use inclusion criteria that are based on how prevalent a certain area is within computer science. The existing publication requirement of the R1 CS institutions combined with focusing on the best conferences of a particular field seems to already nicely capture this.

**Comment by fycus-tree** [comment]
@marcniethammer I greatly prefer this suggestion of a data-driven approach. We could synthesize a list of conferences which have 50 R1 CS institutions publishing in them. Identify common publishing cliques ("conference areas") and do this process without the need for ACM groupings.

**Comment by emeryberger** [comment]
I'd like to first observe that 50 R1 institutions was an arbitrary (and, I admit, US-centric) threshold that I imposed as a minimum bar to cross for filtering research-oriented ACM SIGs of a reasonable size from others, not as a threshold for including arbitrary conferences as areas.

Regarding data, I'd be very interested in seeing a list of conferences (with a higher threshold) but please recognize that a wholesale change that departs from the current organizational scheme is exceedingly unlikely.

**Comment by marcniethammer** [comment]
I don't think there is a need for a wholesale change. But it would be good to establish clear criteria for inclusion in the interest of maximum transparency. Of course, no matter what criteria are chosen, there will always be some level of arbitrariness. But there is no way of avoiding it. 

As the current set of areas have been established with the 50 R1 institution threshold in mind, it seems sensible to me to keep it unless there is a really good reason to change it. Were one to apply a stricter threshold, it may create consistency issues between areas that are already included and future areas that may be considered for inclusion.

From a practical point of view, it would make sense to me to have the currently included areas establish some form of equivalence class. I.e., new areas that are in the same equivalence class as already existing area(s) (i.e., are not weaker in any of the measures) should be candidates for inclusion.

Does this seem reasonable?

**Comment by fycus-tree** [comment]
I would support this as well. Although for me, it came out of seeing how many R1 schools publish in the IEEE systems-focused ICDCS (17% 89 papers, 85 R1) and IPDPS (23% 113 papers, 75 R1). The ACM has the theory-focused PODC (29.2% 40 papers, 37 R1) and SPAA (25% 31 papers, 45 R1), but I'd prefer seeing a category for ICDCS & IPDPS first.

**Comment by themoodymann** [comment]
For what it is worth: Two Turing Award Winners (Amir Pnueli, Leslie Lamport) have presented their Turing Award Lecture at the PODC conference. And PODC is listed as an A* conference in this reasonable ranking: http://portal.core.edu.au/conf-ranks/?search=&by=all&source=CORE2014&sort=arank&page=1. (Quite a few of the conferences that are included right now are not A*.)

**Comment by onerandomuser** [comment]
What about adding PODC below the line in the area of algorithms and complexity, similarly to OOPSLA in the area of programming languages?

**Comment by arashvaezi** [comment]
PODC is one of the best in distributed system conferences. It is strange that CSRanking does not consider this conference!!!!

**Comment by renling** [comment]
@emeryberger  PODC is now listed under SIGACT. So it now can be added to algorithm & complexity, without imposing editorial duties on Emery. Given the premium status of PODC (Turing award speeches as mentioned, and also the highly influential Dijkstra award is given there), there is no question that it should be added. 

I also support the addition of ICDCS, IPDPS, DISC, etc.. But I understand Emery's argument on not wanting to decide CS areas. For these, we need to come up with some clear and object criteria.

**Comment by jlspacemesh** [comment]
Hi @emeryberger, I just came across this thread and wanted to ask whether your opinion on adding PODC to CSRankings has changed since the previous comments were posted above. As @renling has pointed out, PODC has long since been added to the list of ACM SIGACT conferences, which seems to have previously been your main requirement for adding it to CSRankings. If you could reconsider this matter, it would surely mean a great deal to researchers in the area of distributed computing. 

Many thanks, 
Julian Loss
