### ISSUE TITLE
Paper not included

### ISSUE THREAD

**Issue by NoahSD123** [emeryberger/CSrankings#4322]
Hi,
I happened to notice that the following paper is not included in the data for some reason: https://dblp.org/rec/conf/crypto/DodisGSX21.html . It seems that other papers from the same conference are included.

**Comment by emeryberger** [comment]
Thanks for the note. The problem is that CRYPTO is indexed with issue numbers embedded in the title. CSrankings handled up to (3); https://github.com/emeryberger/CSrankings/commit/09ab4e2d74235339076730bcd492a3a20417cf34 adds handling for (4). (This is an annoying practice that I have to handle on an ad hoc basis.) I've changed the logic to handle (4), so the next time the database is rebuilt, that article and others should show up.
