### ISSUE TITLE
Incorrect aliases in dblp-aliases.csv

### ISSUE THREAD

**Issue by srmadden** [emeryberger/CSrankings#4803]
The dblp-aliases.csv file appears to include incorrect aliases for some people.  In particular, the last four lines:

Mary F. Fernandez,Alin Deutsch
Daniela Florescu,Alin Deutsch
Alon Y. Levy,Alin Deutsch
Dan Suciu,Alin Deutsch

Seem to show that a number of people are aliased with Alan Deutsch who should not be.  This is resulting the the publication count for Alin Deutsch being significantly overstated.

In addition the lines just above this also seem to be incorrect, although I have not confirmed that the publication count for Roy T. Fielding is overstated:

Henrik Frystyk Nielsen,Roy T. Fielding
Tim Berners-Lee,Roy T. Fielding

**Comment by emeryberger** [comment]
Thanks for the report! This was due to a logic error or a DBLP error, but the revised logic should hopefully resolve the problem. Fixed with https://github.com/emeryberger/CSrankings/commit/0be1edd871a09a54d91eeed9a8703d9fc8b36162 and https://github.com/emeryberger/CSrankings/commit/d363104817a4e6c545e50ef9b6c637453437ff40. See also:
https://twitter.com/emeryberger/status/1552368003890778112
