### ISSUE TITLE
ICLR has been indexed by DBLP, and as the top conference for ML, it should be included in the rankings.

### ISSUE THREAD

**Issue by Junjie-Chu** [emeryberger/CSrankings#4970]
According to Google Scholar, ICLR's parameters are comparable to ICML and other top conferences. It's time to take it into consideration. 

Thank you for your work on advicing CS PhD and postdoc to select Uni.

**Comment by Ben5000** [comment]
Google Scholar does not provide parameters to conclude whether a conference is considered "top" or not. It is unclear whether ICLR is considered "top" as much as ICML for instance.

**Comment by animesh-garg** [comment]
While Google Scholar is not prescriptive, it provides metrics which could be accounted for. 
At the time of writing this, Gscholar metrics in AI suggest ICLR is the top cited venue in area. 
Subjectively for a venue to bubble to the top in ~10 years of starting is both remarkable and speaks to the popularity and significance inside the community. 

- https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_artificialintelligence
ICLR, Neurips, ICML. 

Infact, it may also be suggested to move KDD under AI along with AAAI and IJCAI. 

There is a listed PR by Sasha Rush to merge
https://github.com/emeryberger/CSrankings/pull/4529

**Comment by Ben5000** [comment]
Citation count depends on the *absolute* number of people (and papers) in a given field. Thus, as a field is bigger, each paper will have on average bigger number of citation (normally; that is, unless citations are completely random, which they are probably not). 
Therefore, absolute values of citation count cannot serve as a reliable approximation to relative "prestige" and "importance" and "being top". It does show popularity, as you've correctly mentioned. But popularity is not the same as "prestige" or "importance".

For instance, if a field (e.g., AI) is huge in comparison to another field X, then even the least important and prestigious conference in AI would normally have a bigger citation count compared to the top venue in X. But it will not be reasonable to include it here.


On the other hand, I do think that ICML and neurIPS should be higher in the ranking than AAAI and IJCAI. But I would suggest demoting the latters, instead of promoting ICLR for inclusion on CSRankings .
