### ISSUE TITLE
Links to wrong profiles in google scholar

### ISSUE THREAD

**Issue by santoshn** [emeryberger/CSrankings#516]
The google scholar profiles are not available for everyone. Further, linked google scholar profiles for some of the authors are wrong. For example, the google scholar profiles of my colleagues Badri Nath (Rutgers) and Vlad Pavlovic (Rutgers) are wrong.

**Comment by emeryberger** [comment]
Scholar links are being generated - it takes a surprisingly long time, and they will be rolling out. Note however, that (a) since they are automatically generated, they are occasionally incorrect, and (b) a number of faculty do not have Google Scholar pages.

I corrected Badri's entry but Vlad Pavlovic doesn't have a Google Scholar page.
