### ISSUE TITLE
A few thoughts on the CSRankings approach

### ISSUE THREAD

**Issue by matthewdgreen** [emeryberger/CSrankings#564]
Hi, I spoke with Emery on Twitter yesterday and he asked me to list some of my concerns on this issue tracker. These are broad and general, and not really a "ticket" per se. I also wrote a blog post that includes a lot of extraneous text:

https://blog.cryptographyengineering.com/2017/11/08/a-few-thoughts-on-csrankings-org/

Here is a summary of the meat of the issues:

First off, what CSRankings is telling us is that we should ditch our co-authors. If I could write a paper with one graduate student, but a second student also wants to participate, tough cookies. That’s the difference between getting 1/2 a point and 1/3 of a point. Sure, that additional student might improve the paper dramatically. They might also learn a thing or two. But on the other hand, they’ll hurt your rankings.

(Note: currently on CSRankings, graduate students at the same institution don’t get included in the institutional rankings. So including them on your papers will actually reduce your school’s rank.)

I hope it goes without saying that this could create bad incentives.

Second, in fields that mix systems and theory — like computer security — CSRankings is telling us that theory papers (which typically have fewer authors) should be privileged in the rankings over systems papers. This creates both a distortion in the metrics, and also an incentive (for authors who do both types of work) to stick with the one that produces higher rankings. That seems undesirable. But it could very well happen if we adopt these rankings uncritically.

Finally, there’s this focus on “top conferences”. One of our big problems in computer science is that we spend a lot of our time scrapping over a very limited number of slots in competitive conferences. This can be ok, but it’s unfortunate for researchers whose work doesn’t neatly fit into whatever areas those conference PCs find popular. And CSRankings gives zero credit for publishing anywhere but those top conferences, so you might as well forget about that.

(Of course, there’s a question about what a “top conference” even is. In Computer Security, where I work, CSRankings does not consider NDSS to be a top conference. That’s because only three conferences are permitted for each field. The fact that this number seems arbitrary really doesn’t help inspire a lot of confidence in the approach.)

Suggestions on how to address this:

More conferences could be added, using some kind of metric to scale point contributions. We could use conference impact scores, or other existing metrics. This wouldn’t fix all the problems, but would at least mitigate the worst incentives.) 

Statistics could perhaps be updated to adjust for graduate students at an institution, and soften the blow of having co-authors. 

More generally, the co-author problem could be addressed by using a softer scale to reduce credit for multi-author papers. The stated logic for the current accounting is to avoid institutions generating higher scores by including more co-authors -- and yet the current approach doesn't even give credit to non-faculty members at the same institution. So this concern (which may be valid when multiple *faculty* co-authors from an institution share authorship) seems completely invalid when non-faculty members are co-authors. In fact, including non-faculty (from the same institution) measurably reduces the overall score of that institution.

Thanks,
Matt

**Comment by adwaitjog** [comment]
I agree with many of the issues mentioned here. Similar to NDSS comment, HPCA architecture conference is also left-off, because of the limit of three. See my previously raised issue: https://github.com/emeryberger/CSrankings/issues/288

I hope we can collectively address all the raised issues. csrankings is a great step forward!

Btw, any talks of a collaboration with csmetrics.org, which seems to incorporate some of Matt's suggestions?

**Comment by impedimentToProgress** [comment]
Alternative viewpoint: I find the focus on top conferences as one of the best points of CSRankings.  It seems that csmetrics already exists for those looking to include more conferences.

**Comment by eagichtein** [comment]
First, again kudos on the rankings and the updates. Despite flaws, this is still a remarkable improvement over usnews reputation rankings.

On the specific issue of conference selection: while many of the selected conferences are indeed "top", a more objective approach of using impact factor, e.g., from Google scholar, to select top-K conferences for each area (e.g., by "impact") would be more defensible and transparent.

For example, in my area (Databases and Info systems), Google scholar "impact" stats are below:
https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_databasesinformationsystems

The top 12 are listed below, and suggest some adjustments to the chosen conferences: 

For Web & IR area, #1 (WWW) and #11 (SIGIR) are currently chosen, skipping over #7 (WSDM) and #8 (ICWSM).

For Databases area, #2 (VLDB) and #6 (SIGMOD) are chosen, leaving out #10 (ICDE) and #12 (CIKM). 

....
1. | International World Wide Web Conferences (WWW) | 77 | 124
2. | International Conference on Very Large Databases | 73 | 106
3. | arXiv Social and Information Networks (cs.SI) | 72 | 124
4. | IEEE Transactions on Knowledge and Data Engineering | 72 | 110
5. | arXiv Databases (cs.DB) | 65 | 96
6. | ACM SIGMOD International Conference on Management of Data | 59 | 103
7. | ACM International Conference on Web Search and Data Mining | 54 | 89
8. | International Conference on Weblogs and Social Media | 52 | 90
9. | International Conference on Web and Social Media (ICWSM) | 51 | 93
10. | International Conference on Data Engineering | 51 | 76
11. | ACM SIGIR Conference on Research and Development in Information Retrieval | 50 | 66
12. | ACM International Conference on Information and Knowledge Management | 43 | 61

**Comment by emeryberger** [comment]
The top tier venues are being slowly revised as I roll out surveys to each community. I do not expect massive changes but some things will shift. These will also inform the "below-the-fold" inclusions (not selected by default, not permalink-able).

**Comment by eagichtein** [comment]
Surveys are fine, but clearly there is some disagreement about the top K conferences for some areas. It would help to be more transparent about the process, and to use impact data like Google scholar as input.

**Comment by fycus-tree** [comment]
@eagichtein 
First of all, there are current outstanding issues on this, namely #366 and #427, where people are proposing adding ICWSM and WSDM. You can see how Emery has typically handled this, with relevant surveys to the community, in #586 or #638 (in a fairly transparent way IMHO). 

I'm a big fan of quantitative metrics, so I agree that something measuring impact would be useful. However, Google doesn't really provide "impact" in a good way. h5-index is h publications with h citations in 5 years. There's many issues with this. A common one is that citations are easily gamed (arXiv papers count, so it'd be nicer to see a "peer reviewed" citation count). Another one is that citations can often be for "disproving" or literature review, and not exactly for impact (many citations in my field are "this is a bad way to do this thing"). The last, and most important, is that h-index isn't normalized by number of papers. So large conferences tend towards larger h-index values, because they have more papers in general. This was highlighted in #586, where 1 of the 3 conferences in a subgroup had accepted nearly 10x the papers, even though it had the same acceptance rate and slightly higher h-index than the other two conferences. 

A better, if slightly biased, way of discovering high-profile conferences was proposed by @marcniethammer in #423. It was roughly-- conferences which have 50 [R1 universities ](https://en.wikipedia.org/wiki/List_of_research_universities_in_the_United_States) publishing in them should be considered. Perhaps at a rate of at least N times in M years (5 in 10?). This is clear, transparent, and somewhat hard to game.

**Comment by eagichtein** [comment]
Yes, I have been tracking these threads. However, I have not seen a survey of the IR/Web search community yet.

To your main point, I agree that Scholar "impact" is not perfect, and it should be used as just one input, e.g., to select candidates for inclusion in the survey. I also love the idea of filtering by participation from R1 universities, though also should include places like MSR, FAIR, Amazon, Google*, etc (in my area, industry labs dominate top conferences like WWW and SIGIR).

**Comment by marcniethammer** [comment]
@fycus-tree  just to be clear, I did not really propose the 50 R1 university criterion. This is part of Emery's standard criteria and it seems sensible to me. I only suggested that being backed by an ACM Sig should not be a necessary precondition for inclusion into csrankings (and is in fact not for some areas that are already included).

In general, I think it would be great if there would be a clearer path to inclusion with a well-defined process to get an area or conference approved or disapproved.

And yes, there seem to be a few outstanding requests along these lines that are waiting to be resolved. In no specific order of significance: #611, #427, #366, #361, #240, #162,  #99, #38.

**Comment by fycus-tree** [comment]
@marcniethammer Ah yeah. I guess your comment just cemented this as a process idea. Instead of checking for ACM SIG support or community surveys, we could start with the R1 50 criteria that CSRankings uses. Then take these conferences and filter them out, group them, weight them differently, whatever. Systematic operations performed on some fairly large, inclusive initial list. 

It would also be nice to find a way to formalize (or weight, or remove, etc.) how groups are created. As I mentioned in #562, I think the current scoring metric (and the way it's coupled with the "groups") is problematic. Additionally, this leads to conference inclusion challenges (e.g. #147 #263 , where HCI & Security folks feel they're too "broad" as groups, leading to 3 conferences limit being hit too quickly. E.g. what if there were separate "computer security" and "network security" groups). 

@eagichtein Yeah I think Emery is conducting surveys as he can. He's a busy guy and I'm sure surveying communities can sometimes take some time.

**Comment by marcniethammer** [comment]
It seems relevant to this discussion that Emery is planning on putting a moratorium on new areas through at least 2018. So I assume this means that conferences in existing areas can be added or changed, but new areas will not be accepted in the foreseeable future.

**Comment by eagichtein** [comment]
thank you for your service to the community.
But... it's been a couple of months, and there is still no resolution of including WSDM (IMHO, top tier) and/or ICWSM (possibly 1st tier) in the Web/IR area. For WSDM, now there are 10+ years worth of stats and impact to go by. Didn't see a survey of Web/IR conferences either. Can we make sure we are counting the right beans?

P.S. Thanks for including NAACL in the NLP area!

**Comment by brendano** [comment]
@eagichtein What exactly is the proposal?  The Web/IR area has 2 conferences currently and you're talking about adding 2 more, but I think Emery has a rule of limiting to 3 per area.  Is the proposal to kick other conferences out?  I feel like many people keep posting commentary about one or two conferences they want to add, but without a clear and coherent assessment of the tradeoffs and how it fits into community practice.

Web, IR, and Data Mining are a genuinely complicated set of areas and I personally find it difficult to determine how to draw boundaries to fit conferences in to.  You could argue that WWW and KDD should be in the same area.  You could argue WSDM and SIGIR should be together and WWW separate.  You could even argue ICWSM should be in HCI...

**Comment by andrewcmyers** [comment]
Some more comments on the co-author incentives problem here: #265

**Comment by csirac** [comment]
I would like to add my support for determining the "top venues" for each field in a quantitative and open-source way. Much more ideal would simply to give each venue a weight that is incorporated into the overall score of a publication, rather than zero credit for a venue that is not a top venue.

To me, the downside of including only two or three venues per area, and not counting journals, is clear: these top areas will be overwhelmed with submissions, to the extent that they will likely be unable to review them all with the care they deserve (examples: ICML had 2500 submissions and AAAI had >7000 submissions this year). Also, the likely outcome is that secondary conferences will eventually disappear, and power will be dangerously concentrated in the committees of these few conferences.

For these reasons, if csrankings fails to incorporate other venues in some way, I would encourage others to extend it and include them. You've got a partially quantitative ranking, which is a huge improvement over USNews. Let's finish the job.

As far as co-author incentives, I think csrankings has it exactly right: it encourages only substantial contributors to the work to be authors. In my opinion, csrankings provides one of the few incentives against [author inflation](https://www.nature.com/nature/history/full/nature06243.html).

> First off, what CSRankings is telling us is that we should ditch our co-authors. If I could write a paper with one graduate student, but a second student also wants to participate, tough cookies. That’s the difference between getting 1/2 a point and 1/3 of a point. Sure, that additional student might improve the paper dramatically. They might also learn a thing or two. But on the other hand, they’ll hurt your rankings.

If the paper is improved dramatically, presumably its chance of acceptance would improve as well. Also, as Emory has commented elsewhere, with more authors, papers can be produced faster.

**Comment by jefhai** [comment]
I feel like we need a lot more transparency and a disclaimer on CSRanking... that it is imperfect. Because any such flaw that can be studied by professors and abused has a real life impact on students selecting programs. A simple example of a flaw is when a college forgets to remove old faculty or doesn’t add missing faculty.. that’s an issue! 

Because smart students are going to schools with good faculty in mind, but also based on prestige that may be given here that could have real issues with it.

A real example of this is StonyBrook University recently touted CS Ranking of top 25 in certain areas... I haven’t reviewed them but I’m sure some of their faculty no longer work there.. or new ones aren’t on the list.. So the real danger is slight misinformation. Which is why I think a disclaimer is needed. That this is a community wiki that isn’t reflecting real time.

And how many other schools suffer slightly because people aren’t reviewing their CS Rankings..

**Comment by kno10** [comment]
IMHO the ranking, as is, is **very harmful to the scientific community**.

Because it highly limits the number of venues that are "worth" submitting to from a ranking point of view. Some venues literally get *spammed* by low-quality submissions now, and the randomness of peer review will likely cause a lot of very bad publications to make the cut (and good ones to be rejected and drowned).

Ask two program committees, and you'll get two very different results: http://blog.mrtz.org/2014/12/15/the-nips-experiment.html

Of course csrankings.org is not the only thing to blame here. But it contributes by completely ignoring all but the _very_ top venue. Consider AI (NIPS and ICML only) and data mining (KDD only), for example.
There are many more good conferences than 2 respectively 1...
Similar problems already exist with inclusion (or non-inclusion) in other indexes such as ISI WoK, and impact factor. Such evaluation can cause harm: https://www.technologyreview.com/s/608266/the-truth-about-chinas-cash-for-publication-policy/

What is worse: "citation cartels" (that can be detected with modern analysis methods - and some citation data is becoming increasingly available finally - and that hence could any time be called out and probably even 'punished' in rankings), or submission spam that overloads conferences, decreases review quality, even makes reviewers give up reviewing, and ultimately causes more bad papers get accepted?

Surely citation indexes aren't perfect, but IMHO they are still better than this extreme elitism.

**Comment by fycus-tree** [comment]
@kno10 A good follow up is the [Design and Analysis of the NIPS 2016 Review Process](https://arxiv.org/abs/1708.09794) which suggests the messy middle is about 30% of papers.

**Comment by kno10** [comment]
@fycus-tree to quote that paper: "Specifically, if we remove the bottom 70% of papers (and none of the top papers) then we see that the inter-reviewer agreements are near-random, but farther from random otherwise."
So the non-middle "top" part is pretty much 0. There are bottom 70% apparently clear rejects (up from 55% the year before), and 30% middle that are "near-random" in their outcome?

**Comment by fycus-tree** [comment]
@kno10 I don't think this issue is the right place to discuss this, but yes. The bottom 70% the reviewers agree about. The top 30% are where the reviewers don't agree with each other. The previous year removed the top 15% and bottom 40%. I don't think this issue is completely clear but I just wanted to have a pointer to that work here
