### ISSUE TITLE
CSrankings has omitted all the papers published before 2010 on ACM SIGCSE

### ISSUE THREAD

**Issue by yjwtheonly** [emeryberger/CSrankings#5803]
I learned from my previous question that CSrankings only lists publications with 6 or more pages（ https://github.com/emeryberger/CSrankings/issues/5788 ）.

However, I found that according to this criterion, all articles published before 2010 on ACM SIGCSE will not be included. Because during this time period, the upper limit for publishing articles was 5 pages.

This is the result given by CSrankings with a cutoff date before 2010 on ACM SIGCSE:
https://csrankings.org/#/fromyear/2002/toyear/2010/index?csed&world , and the result is empty.

And here is an example, all the papers published in ACM SIGCSE in 2010 listed by DBLP are:
https://dblp.org/db/conf/sigcse/sigcse2010.html#ZhangL10 ,
and you can notice that they are all at most 5 pages. 

So, I think this criterion may have some flaws.

**Comment by emeryberger** [comment]
The only records I have for SIGCSE - which indicate which papers are research article - are in the file https://github.com/emeryberger/CSrankings/blob/gh-pages/sigcse-research-articles.csv. These were painstakingly assembled and I don't think there are likely to be any updates for articles published before 2010 (which is why none show up). In addition, the page length minimum is uniform across all areas of computer science and is not likely to be changed anytime soon.
