### ISSUE TITLE
Add CS Education Researchers

### ISSUE THREAD

**Issue by SethPoulsen** [emeryberger/CSrankings#6173]
I'm thrilled to see the addition of CS Education as a research area on here. Adding SIGCSE is a great start, now it would be great if we could start adding in a bunch of researchers who were not previously on the site. 

This is only the beginning, just people I know off the top of my head. I would love for others to add more people as comments here and we could add them all in one go or in phases over the course of a few Pull requests. Thanks!

University of Illinois Urbana-Champaign: 
- [x] Kathryn Cunningham
- [x] Colleen Lewis

Utah State University:
- [x] John Edwards
- [x] Seth Poulsen (myself)

University of Utah:
- [ ] Eliane Weise

University of Michigan:
- [ ] Barbara Ericson

University of Florida
- [ ] Kristy Boyer (currently mistakenly under NCSU) 

Carnegie Mellon
- [ ] Kenneth Koedinger

Brown University
- [ ] Kathi Fisler

Duke
- [ ] Kristin Stephens-Martinez

Berkeley
- [ ] Dan Garicia

**Comment by cruzizu** [comment]
both SIGCSE and ITICSE are international conferences sponsored by sigcse.org and usually  ranked at the same level - eg CORE A ranking.  However this ranking is ignoring the latter, taking a  US centric view.

**Comment by SethPoulsen** [comment]
Hi Cruz, 

I agree it would be nice to add ITiCSE, that seems like it should be made as a separate issue than this one though, right?

Related to this issue though, maybe you could add other CS Ed researchers from outside the US to the list I made--I started out with these mostly because they are the people I know--I would love for others to add more to the list so we can get a fuller picture!

**Comment by cruzizu** [comment]
It was not clear to me how researchers are added,  someone has to request it? Not sure why my name is already there.  I thought they should be picked up from DLBP as they published. Just noted I was listed with 3 publications, the SIGCSE ones and none of the ITiCSE were listed. 

Currently missing many, just to list a few Professors 

Quintin Cutts, University of Glasgow (leading a large team)
Erik Barendsen, Radboud University
Lauri Malmi, Aalto University (leading a very large team) 
Arnold Pears, KTH Sweden

However, I am not sure this is the best method, to rely on who knows who and has the time to report them. 
Also  ICER should be added, so that all three  top conferences (SIGCSE,ITiCSE and ICER) are included.

**Comment by SethPoulsen** [comment]
I am not the one who makes the decisions here, but my best guess is that it is done this way (manually) because it isn't really possible to match Professors to Universities using DBLP data. 

I also agree that ICER should be added too. 

Most of the other research areas on the site have the top 2-3 conferences listed, so we really should have SIGCSE, ITiCSE, and ICER for the CS Ed research area.

**Comment by katieirenec** [comment]
Myself (Kathryn Cunningham) and Colleen Lewis were added in #6803 . 

I was asked to remove Geoffrey Herman because he is not a tenure-track faculty (even though he regularly advises CS PhD students). Many of the CSEd researchers on this list face the same challenge (Kathi (research prof), Kristen, and Dan (teaching profs)). If Dan has the "security of employment" that the UC system sometimes offers it may be possible.

I don't know if Barb Ericson can solely advise CS PhD students, which is another of the criteria. Any PR with her included will have to make that clear since she's in the School of Information.

**Comment by katieirenec** [comment]
I submitted a PR to move Kristy to Florida #7237

**Comment by katieirenec** [comment]
Looks like Eliane is now in CSRankings.

I submitted a PR to move R. Ben Shapiro from Boulder to UW #7261

**Comment by emeryberger** [comment]
Closing this issue since PRs are the mechanism for adding and updating the database.
