### ISSUE TITLE
Why is Israel in Europe?

### ISSUE THREAD

**Issue by Camel-light** [emeryberger/CSrankings#6957]
This isn't about politics, but why is Israel placed in the Europe category? Seems inaccurate as most sources define it as Middle Eastern (Enc. Britannica) or  West Asian (Wikipedia) country.

**Comment by StEvUgnIn** [comment]
I agree. Israel is not part of Europe. Can anyone comment on this?

**Comment by jay-tau** [comment]
Agreed.

According to https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file) as well, Israel should be in Asia and not Europe.

I have already created a PR: https://github.com/emeryberger/CSrankings/pull/6869 for this

**Comment by YuvalFilmus** [comment]
Israel is eligible for grants from the European Research Council, participates in the European song contest (the Eurovision), participates in the European leagues in soccer and basketball, and so on. In contrast, it has few ties to entities in the Middle East or elsewhere in Asia.

**Comment by StEvUgnIn** [comment]
I think this conversation is concerning... 

If you disagree, you can consider the portal of the Council of Europe for reference:
https://www.coe.int

Geographically speaking Israel should not be located in Asia, since the territory belongs to the African and Arabic tectonic plates. In my opinion, Israel and the following countries should be listed in their own category named Middle East for the consensus: https://en.wikipedia.org/wiki/Middle_East

**Comment by YuvalFilmus** [comment]
Would you put University of Hawai'i in Asia?
Geography is not everything.

**Comment by StEvUgnIn** [comment]
> Would you put University of Hawai'i in Asia? Geography is not everything.

We can disagree from time to time, but it matters to show integrity in this matter.

**Comment by Camel-light** [comment]
> Israel is eligible for grants from the European Research Council, participates in the European song contest (the Eurovision), participates in the European leagues in soccer and basketball, and so on. In contrast, it has few ties to entities in the Middle East or elsewhere in Asia.

> Would you put University of Hawai'i in Asia? Geography is not everything.

The analogy is not appropriate, as Hawaii belongs politically and jurisdictionally to the USA nation. Israel doesn't belong to France, Germany, nor any EU nation. Israel is not part of key European academic programs, such as Erasmus+ as described [here](https://erasmus-plus.ec.europa.eu/programme-guide/part-a/eligible-countries). Indeed, it is expressly placed in § 3. of "Third countries not associated to the Programme", together with Algeria; Egypt; Israel; Jordan; Lebanon; Libya; Morocco; Palestine; Syria; Tunisia.

Even if it would, belonging jurisdiction is not the relevant criterion here. Csrankings states "_by continent_" as the classification criteria, and continents' boundaries are not defined by size of economic relations. Here is Wikipedia's definition: 
>  By convention, continents: "are understood to be large, continuous, discrete masses of land, ideally separated by expanses of water."
[Link](https://en.wikipedia.org/wiki/Continent#Definitions_and_application)

If we would use economic ties as a principle, all sorts of institutions would have to be changed into different continents, for example _American University of Beirut_ is placed in Asia [here](https://github.com/emeryberger/CSrankings/blob/gh-pages/country-info.csv), even if it is chartered in New York and its degrees officially registered with the New York Board of Regents.

The csrankrings project itself seems to follow spatial location to define the continent: [Here](https://github.com/emeryberger/CSrankings/blob/gh-pages/continents.js)

**Comment by StEvUgnIn** [comment]
Great insight @Camel-light

**Comment by emeryberger** [comment]
Israel has been included in Europe since CSrankings' inception in 2016, when the first non-US institutions were added. Almost eight years has elapsed with no discussion of this topic until now. I note that the Israeli press itself did not seem to find this classification surprising in the least (https://www.jpost.com/business-and-innovation/all-news/article-717204). Given this background, and in light of the current political situation and the controversy around the Israel-Hamas war, there will be no changes to this classification in CSrankings for the foreseeable future.
