### ISSUE TITLE
clarification regarding decision on medical image analysis

### ISSUE THREAD

**Issue by marcniethammer** [emeryberger/CSrankings#762]
Hi Emery,

I am trying to understand your editorial decision of not including medical image analysis as a top-level area in CSrankings ( #611 ).

Could you clarify if this decision is based on the perception that

- medical image analysis is not an area of computer science
- and/or that it should not rise to a top-level area?

Many thanks in advance for the clarification.

**Comment by wentaozhu** [comment]
I think it is better to add medical image analysis because many professors working on computer vision also work on medical image analysis especially in US. Also, professors working on medical image analysis submit their papers on MICCAI for the medical image analysis papers. And they consider the MICCAI is a top conference on the area comparable to CVPR because conferences like CVPR, ICCV only have one session (2%) for medical image analysis which is not a main conference for the area.

Considering that the robotics, HCI, economics and computational biology are in the CSrankings, I think it is better to add medical image analysis.

**Comment by marcniethammer** [comment]
I agree. It is puzzling to me why 'economics + computation' for example is included, but medical image analysis does not make the cut even though it appears to be a significantly larger area in CS.
(I am totally in favor of including economics + computation, but I think the area selection is inconsistent.)

I suppose adding many new areas may create issues when using the geometric mean to compute overall scores. If this is the argument though, it may be better to simply have an additive score (at least as an option). This would allow adding new areas without really impacting the others. I.e., if an area is in fact small it would not have a large impact on the ranking and hence everything could be integrated gracefully. (See also #562 for a discussion on weightings.)

**Comment by marcniethammer** [comment]
Hi @emeryberger. Do you have an update on this issue? I understand, of course, that what to include and not to include is always to a certain extent a judgement call and I am grateful for your efforts in running this site.

However, based on the relatively recent analysis of @fycus-tree (#859 and #857) it appears as if there are currently some inconsistencies in the included areas. Some areas do not appear to fulfill the minimum requirements as spelled out in the FAQs (#857), but are included. Other areas fulfill the criteria, but are not included; in my own biased view, medical image analysis (#611) is an example of one of these areas.

Do you have a plan to revisit the inclusion criteria and what areas are included, should be added, or should be removed? I'd be happy to help with this effort if you like. I am sure others would be happy to help as well. I also believe that it could be very useful to form a csrankings board to help you with running the site and to formalize and document decision processes.

Thoughts?
