### ISSUE TITLE
Please shut down CSrankings, for the sake of science

### ISSUE THREAD

**Issue by jonsterling** [emeryberger/CSrankings#771]
CSrankings plays a harmful role in the scientific process. It encourages the following odious outcomes:

1. Identification of scientific contribution with publication metrics. Why is this bad? At least in my field, many of the most influential papers (in the sense of defining the terrain for future scientific advances) were not published in prestigious conferences or journals (indeed, some of the most important such advances appear only as notes on the author's website, or on the Arxiv).

2. Reduction of individual scientific practice to competition over publication metrics. The display of individual metrics for faculty accelerates the devastating trend of short-term publication-oriented piecework being substituted for the big-vision / long-term scientific work which led to the advances which have utterly defined the current scientific landscape.

3. Discourages collaboration, including collaboration with students. This scientifically poisonous view has already infected students at my university (Carnegie Mellon University--apparently this is the "Best" university according to this website, thanks!); I have seen students explaining to other students that it is important for them "not to collaborate" in order to maximize their metrics. Make no mistake that this deviation is a direct result of the culture encouraged by CSrankings, which is not at all a neutral tool. (See also tickets #770 and #564 and #589.)

As a young scientist who is just beginning to make my first contributions, I implore you to shutter this website and find another way to gauge the importance of scientific work and locales.

**Comment by adrieng** [comment]
Seconded.

I understand that the purpose of CSRankings is to improve CS research assessment and give a relevant metric to undergraduate or graduate students. But I believe that this attempt at reform is actually making things worse, for all the reasons @jonsterling gave. In my opinion, one should oppose quantitative metrics vehemently rather than try to extend their reach.

**Comment by jonsterling** [comment]
@emeryberger You can close these tickets all you want, but it won't stop the scientific community from unleashing a *hurricane* of such tickets! Let's discuss this in a mature way, and come to a conclusion that resolves the contradiction between CSrankings and the scientific community.

Another point I wanted to raise is that this style of ranking also ignores one of the most important parts of the scientific process, which is teaching: and not just the work that takes place in the classroom, but also the work to develop new and innovative curricula. I have no doubt that the emphasis on teaching in departments like CMU and Indiana has been absolutely essential to developing their excellence in other areas.

**Comment by emeryberger** [comment]
A ticket that starts as "Please shut down CSrankings, for the sake of science" is not the entrée to a "mature" discussion.

**Comment by brunyuriy** [comment]
I think it is important to note that there is a difference between "creating an imperfect ranking in a world with no existing rankings" and reality.  The reality is a world in which many students (and others) use US N&W rankings, which are baseless and inaccurate.  I agree that a ranking cannot capture the entirety of our jobs and no ranking will be perfect.  However, given that an inaccurate ranking dominates, I see value in making available a more transparent, more accurate, data-based ranking (even if in some ways it is imperfect).  That's what csrankings provides.  So arguments that rankings in general are bad miss the point that csrankings attempts to improve on the status quo of rankings, rather than to claim some (unachievable) perfection.
