### ISSUE TITLE
Policy regarding faculty members going on industry "leave"

### ISSUE THREAD

**Issue by fycus-tree** [emeryberger/CSrankings#823]
Many faculty in Computer Science are taking industry leaves of some form or another. It's a little hard to confirm/deny the extent to which these faculty are still affiliated with their university. I'm not sure if either Emery or anyone else has a clear policy that would be easy to verify. I thought I'd make an issue for this specific topic. 

This was part of the discussion on 8a8d0776db9a2a7182bab612180f346cce2a4e90

Quoting Yann LeCun on FAIR's policy, which seems to lean on "they're still at the university", but this has come up before at #470

>  This NYT piece by Cade Metz erroneously qualifies this evolution as a "brain drain" from academia. But Facebook is careful not to deplete universities from their best faculty, by making it easy to maintain sizeable research and teaching activities in their academic labs. In fact, making these part-time splits possible is precisely the reason why we have been establishing labs in New York, Paris, Montréal, Tel Aviv, and now Seattle and Pittsburgh. It is the proximity to leading universities with talented faculty, and the existence of a local talent pool that attract us. Unlike others, we work with universities to find suitable arrangements and do not hire away large numbers of faculty into full-time positions bottled up behind a wall of non-disclosure agreements. We contribute to local ecosystem.
> Faculty who join FAIR part-time practice open research, teach courses, advise PhD students, and participate in the life of their department.

Quoting my own comment on that commit
> there's a challenging question of what it means to be "on partial leave". For example, what if they're on campus 3 days a week? What if the company office is located on campus (or right across)? What if they're utilizing a department policy that lets them take a 2-3 year partial-leave sabbatical?

> Some other high profile candidates who are "walking the line", and currently including in CSRankings
> * [Dieter Fox](https://homes.cs.washington.edu/~fox/) at UW states that he's _"currently on partial leave from UW and joined Nvidia to start a Robotics Research Lab in Seattle. Stay tuned for more information and the location of the lab._"
> * [Bill Freeman](https://research.google.com/pubs/WilliamTFreeman.html) at MIT is listed by Google as _"a Senior Research Scientist at Google, managing a team within Machine Perception doing research in vision and graphics."_
> * [Deva Ramanan & Simon Lucey & James Hays](https://www.argo.ai/single-post/2017/11/21/How-We%E2%80%99re-Working-with-Universities-to-Stay-on-the-Cutting-Edge-of-Research) at CMU & Georgia Tech are _"spending time at Argo AI"_ but also _"continue to teach and maintain their work and research at their universities"_ per [a press release](https://www.ri.cmu.edu/argo-ai-collaborates-with-cmu-georgia-tech-researchers-on-self-driving-cars/)

**Comment by fycus-tree** [comment]
Some proposed policies

1. **Faculty who serve as the primary advisors for PhD students are included**. This can be pretty easily to verify and check. An additional requirement may be that they teach at least one course every two years. 
2.  **Faculty who are primarily on a paid leave appointment are not included**. Example criteria here would include, do they list their industrial partner as their affiliation on their papers? Do they present themselves are primarily spokesmen/women for the company? Do they not teach classes anymore?

**Comment by animesh-garg** [comment]
I noticed that Fei-Fei Li is not listed in Stanford CS Lists. She is on leave but she is actively splitting her time, and advising students at Stanford. As for the courses criterion, students from the lab are stand-in instructors regardless of her availability. 
Could we fix this?

**Comment by fycus-tree** [comment]
@animesh-garg To the best of my understanding, she's part-time at Stanford, and full-time at Google. Her students teach her classes, and their advising is often covered through part-time, year-long Google internships. That would make her not eligible under the current criteria. There is a list of such faculty in [old/industry.csv](https://github.com/emeryberger/CSrankings/blob/gh-pages/old/industry.csv)

I tried to have this specific issue to discuss a **general policy** about what should be inclusion criteria. If you think Fei-Fei should be added back, can you make a pull request for that discussion? For this issue, do you have any thoughts about what the policy should be, in general, as this impacts many faculty and not just your own adviser ? 😄

**Comment by animesh-garg** [comment]
This is a fair point. However complete exclusion results in incorrect counts which may skew rankings. For instance, Stanford suffers a lot if Fei-Fei Leaves, same with NLP at UW with Luke and Yejin.

In case of Fei-Fei, most of the points are true except for the student advising. Most students are not google affiliates. Out of 10 odd students, only 1 is long-term intern. And I would think she should be added back into the list. 

At the same time, I do agree that this is a more subjective matter. A possible list of suggested criterion can be:
(a) if they still maintain an active lab? there should be students who are not all affiliated with their corporate position.
(b) Has the lab published with PI as last /second last author where others are not primarily at the company?
(c) Are they within 2 years of the allowed leave? Usually, it is after 2 years that universities want them to come back. 
UW is a special case which allows longer-term outside affiliations. And it will increasingly become the norm. 
(d) If they were tenured/tenure-track -- have they given it up? CMU being an exception of this criterion -- there are a number of full-time research track faculty - Abhinav Gupta was one.

**Comment by fycus-tree** [comment]
@animesh-garg 

1. an interesting, somewhat orthogonal idea, is if CSRankings adds a "include professors on industry leave" checkbox that allows these industry faculty to be included.
2. Currently, the faculty on leave don't skew the rankings that much. Between the fact that top universities are hardest hit by faculty leaving for industry and the current aggregation metric being more about punishing "lack of work" than rewarding "presence of work". If you add the industry people back in, the rankings don't really move much. 
3. I think, as you point out, (c) is a challenging criteria. I would replace it with having been the primary course instructor in the last two years (actually giving lectures), as that's easier to verify. 
4. A slight correction is that [Abhinav Gupta](http://www.cs.cmu.edu/~abhinavg/) is tenure-track, not research-track (which also has "tenure") at CMU. A comparable example would be [Simon Lucey](http://www.simonlucey.com/), who is a research-track professor (which at CMU still allows teaching of classes, primary advising of students). 
6. My original post has 5 more faculty who are now on partial leave and Emery has yet to remove them from the rankings. They present interacting cases of what it means to "be on leave"

**Comment by deniszorin** [comment]
@fycus-tree  Kyunghyun Cho is not on any sort of leave, partial or full (I am his department chair).

**Comment by fycus-tree** [comment]
@deniszorin what does this have to do with me? Kyunghyun Cho isn't mentioned in this issue?

**Comment by animesh-garg** [comment]
@fycus-tree Kyunnghyun is listed in the industry list when he should not be.

**Comment by fycus-tree** [comment]
@animesh-garg Maybe wait for a response to #861 ?  Or simply have that conversation there. The goal here is to find a good answer to "what should a general policy look like?"

EDIT: If you're new to using git, there's this feature called git blame that tells you what commit each line came from. Try it out for yourself, GitHub even has [a web-frontend](https://github.com/emeryberger/CSrankings/blame/gh-pages/old/industry.csv).

**Comment by deniszorin** [comment]
@fycus-tree I did submit a pull request.  I've noticed the name on the list of examples of people in industry posted here and incorrectly assumed you have compiled it, sorry about the confusion.

**Comment by nasmith** [comment]
There's no good way to draw the line (including and especially the way it's currently being drawn) because you can't get accurate, up-to-the-minute data on every single person's status, and statuses and names of different kinds of "leave" are not comparable across universities. (Note that "leave" status, just like employment status, can change at any time.) I could list a ton of people who are spending more time on industry engagements than I am, but haven't been removed (sorry, I have other work to do). Under the current policy, this website becomes next to useless for understanding university AI-and-related groups. Perhaps a better (and easier to track down) criterion would be, "did the person teach a course at the university in the last year?" As is, I cannot recommend students interested in my research areas use this site any longer, as it's incredibly misleading.

**Comment by rahmati** [comment]
This is not necessarily foolproof. How would you detect/deal with someone who has bought out their teaching requirement? Not count them?

**Comment by nasmith** [comment]
How much "buying out" is acceptable?  At many universities, faculty with grants routinely buy out of one quarter or semester.  That's likely to be reflected in their research productivity, because they have more time to advise students and write papers.  And how do you account for different teaching loads in different departments?

I am not claiming there is a foolproof or non-arbitrary way to do it; all you can do is try for a criterion that's not *misleading* like the current one, and that continues to be easy to understand.  "Did they teach at least one course in the past year" seems to meet that criterion, but data collection is obviously non-trivial.

**Comment by xliucs** [comment]
There are still few issues worthy to note. 

1) inaccurate information regarding faculty's current affiliation 

For example, Anind Dey has left CMU and joined UW information school, which actually misled me to put him in my PhD application this year.  

2) outdated information about affiliated professors in CS departments.

As far as I know, faculty members at MIT Media Lab could also advise students at MIT EECS, and faculty members at UW information school or HCDE departments could also advise students at UW CS. Those affiliated professors sometimes play big roles in the ranking metric. For instance, Yun Fu, a professor in ECE at Northeastern, is ranked No.1 in the brach of northeastern, and he noted that student could only apply for PhD program in computer engineering instead of computer science in his website. The similar situation also applies for Tsuhan Chen at Cornell etc...

**Comment by fycus-tree** [comment]
@xin71 this is a host of other, unrelated issues. There is no central faculty tracking system, affiliation changes have to be submitted by users. For example, Anind Day's information is incorrect on his faculty website and on his wikipedia page. It's also not clear that Tsuhan Chen is at Cornell, it seems his affiliation also needs an update. The inclusion criteria question is really for #480 , but if Yun Fu can't advise CS students he should be removed for the current criteria. 

If you notice these issues with affiliation, I ask that you submit a pull request to fix them. Emery runs this website by himself on top of his normal professor responsibilities, so he can only do so much.

**Comment by neubig** [comment]
I really like csrankings as a very good way to give my students a list of faculty members that they should take a look at if they're interested in working in a particular area, but I agree with @nasmith that the site really loses a lot of usefulness if there is a strict policy of excluding people that also have positions at companies. For example in my area of NLP, UW is a great place to do NLP because Yejin Choi, Noah Smith, and Luke Zettlemoyer are there, but currently they're all excluded due to this policy. Also Kyunghyun Cho is excluded from NYU, etc. etc.

For my purposes, the ideal policy would be "They are considered not affiliated if they have a dual position, *and* there is an indication of significantly reduced participation in academic activities such as not teaching classes or a statement such as 'I am currently on leave and not taking new students' on the web site."

I understand that this takes a significant amount of manual searching/work, but this is true for the site in general, and I think with a site of this size it's necessary to rely on community contributions to keep it going. Anyway, food for thought: I think the site is a great resource for students who are interested in finding potential advisors in their field, and would love to see it stay that way, even in the face of the recent wave of faculty dual positions in industry.

**Comment by fycus-tree** [comment]
@emeryberger re the recent CMU & FAIR connection, the [CMU press release](https://www.cs.cmu.edu/news/hodgins-gupta-join-facebook-ai-research) states 

> Hodgins, a professor of robotics and computer science, and Gupta, an associate professor of robotics, will work part-time with Facebook, maintaining their teaching and research duties at CMU. This dual-affiliation model is common across FAIR

On the other hand, the [FAIR announcement](https://newsroom.fb.com/news/2018/07/facebook-ai-research-expands/) says
> Both Jessica, professor of robotics and computer science, and Abhinav, associate professor of robotics, will retain their Carnegie Mellon University positions part-time.

and continues to list faculty that are part-time of this dual-affiliation model, including the following still included on CSRankings
> Devi Parikh and Dhruv Batra with Georgia Tech, Pascal Vincent with Université de Montréal

**Comment by vzhong** [comment]
I agree with @neubig . I would go so far as to say that I find it hard to take this ranking seriously if it ranks UW 20th in NLP. Also for the record, all three NLP faculties Graham listed currently assume full advising and teaching duties at UW.

**Comment by djg98115** [comment]
Full disclosure: I hold a leadership position in the UW Allen School, so I have both a strong incentive and additional context on the particular issues of UW's Choi, Smith, and Zettlemoyer.

But given that, let me try to weigh in more generally before returning to those particular situations.

First, while I appreciate the goal of not including faculty "essentially no longer acting as faculty or who have functionally left", I think removing someone for "non-sabbatical industry leave" is, in many cases, far more aggressive than that.  There's no perfect rule and these situations can be both complex and opaque (i.e., not all information is always even known publicly), but given that I would advocate for a lighter touch.  Unless someone has "clearly acted as though they're gone mostly permanently" or far more than a year has elapsed, it just seems too hard and error-prone and volatile to call industry activity a 'departure' when it often isn't.

Here's some provocative math: At most [?] universities, with no out-of-the-ordinary approval procedures or special treatment, a faculty member could choose to consult up to 20% time ("1 day a week") during the academic year and full time during the 3 months of summer.  .2 * .75 + 1 * .25 = .4.  If we compare that against a faculty member who is truly "50% for 12 months", I think it's hard to call one a "100% faculty member" and the other a "0% faculty member".  Similarly, is someone serving in a time-consuming leadership position (like a chair or dean) really "available to advise students" more than someone doing 50/50 with a company?

For all these reasons and probably a dozen more, I would, to repeat myself, advocate for a significantly "lighter touch".  For example, while delaying 1-2 years before removing someone who appears to be on perpetual leave might create a lagging-indicator problem for prospective graduate students, it avoids jumping-to-conclusions and is much easier to implement equitably.

Okay, now to return to Choi + Smith + Zettlemoyer.  They really are not functionally gone in any sense: on campus regularly, full student loads, significant department service, continuing to secure grants, and, yes, teaching.  The discussion above proposed a proxy measure of "teaching classes".  I see the appeal (transparent, hard-to-fake, meaningful), though like any proxy it's not perfect.  

If the community in general (and in particular Emery, of course), are comfortable with that, perhaps provisional, criterion -- perhaps teaching is a sufficient but not necessary criterion for counting as faculty -- then the UW issue is clear.  Go to https://www.cs.washington.edu/ -> Academics -> Time Schedules -> 2018-2019 Teaching Schedule to see in a public place:
 * Choi: Graduate quals course in NLP
 * N. Smith: Two undergrad courses, one NLP-proper, one a capstone project course in the NLP space
 * Zettlemoyer: 1 evening Masters course in NLP and 1 undergrad course in AI
As calibration, our nominal teaching load for tenure-track faculty is 3 courses per year (reading seminars and other pseudo-courses don't count; all the above are real in every sense), but it's quite common to buy out of 1 of the 3.

Zooming back out, we as a field will continue to find our relationships between academia and industry challenging.  There are no simple or perfect answers -- it's not always clear what's best for graduate students, the field, etc.  But they're challenges we should confront by embracing the complexity and nuance.  CS Rankings is, of course, "just a website", but my advice is let's not rush to to say our colleagues "aren't faculty members anymore" until we're sure.

**Comment by brendano** [comment]
I agree UW at number 20 or whatever doesn't seem right.  I found this issue because I was wondering why I was seeing that just now.

I think everyone agrees the site ought to be as accurate as possible, and the question "both a company and a university claim the same person works for them both. Who to trust?" is just hard without privately available / sensitive information.  The two most constructive tests for this I think I've heard so far, that are based on publicly available information and relatively few judgment calls:
 - Official affiliations/titles on the department's webpage. (Suggested by @deniszorin in another issue.)  Necessary but not sufficient?  I personally don't always find this information completely credible by itself, since departments are incentivized to upsell their affiliated faculty's involvement.
 - Recent (last year or so?) teaching record (suggested here).  This one is nice because it's a publicly observable indicator of the person actually spending time and energy.  Sufficient (along with previous), but not necessary?

Are there any others that can be brainstormed?  What about recent research output with students in said department?  That seems like an obvious criterion why we think UW is active in NLP, and a very important factor in whether a prospective grad student should go there.  Like the teaching criterion, this is less automatic to evaluate, of course, but maybe usable for this situation.

I would think everyone agrees that on-campus research engagement (lab meetings, working with students, etc.) would be a sufficient indicator, but that information is rarely public.

There seems to be a cross-cutting issue of good faith assumptions, that I think might be underlying some of these discussions.  Is the claim by a department chair, fellow faculty, or the faculty themselves, that someone is working at an institution full- or near-full-time, a sufficient piece of evidence for a project like this website?

I've also noticed
 - Emery seems to have recently used a criterion that's something like "their personal homepage announces they are on leave in industry" (5b3e15bce1d2fd5d015cac4bb749949083c2c1ae)
 - I'm less enthusiastic about using press coverage as a source.  I've also noticed UW people are especially unhappy about that particular NY Times article.

**Comment by brendano** [comment]
I think this is old news, but Emery did publish a precise definition of the "full-time" criterion, on http://csrankings.org/faq.html (quoted below), as a 75% appointment.  I would think this addresses at least some of the issues mentioned above, though of course whether 75 is the right threshold or not could be debated.  I am under the impression Emery may consider this issue closed.

> What are the criteria for including faculty?
> --
> The criteria for inclusion are that anyone who is a full-time, tenure-track faculty member on a given campus who can solely advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students. Note that full-time means an at least 75% appointment for the entire academic year.

**Comment by emeryberger** [comment]
Correct, thanks @brendano. One thing I have considered is to add a checkbox to allow people to show up in the database who remain affiliated with a university but with a lesser appointment (e.g., 50%).

**Comment by neubig** [comment]
This is described in the issue here: https://github.com/emeryberger/CSrankings/issues/1843

I think this change is a good thing, for the reasons I mentioned above.

**Comment by nasmith** [comment]
Unsubscribe.  Better tools with more accurate data, less
arbitrarily-defined criteria, and more consistent application of those
criteria have emerged.

**Comment by neubig** [comment]
@nasmith Would you mind providing some suggestions? I still don't know of a better site that could help students applying to grad school find a list of potential advisors in a particular field (NLP for example).
