### ISSUE TITLE
Should we add a weighted ranking that put weights on areas?

### ISSUE THREAD

**Issue by weikengchen** [emeryberger/CSrankings#828]
Because it is clear that some areas in CS are much easier to publish top conferences papers.

**Comment by emeryberger** [comment]
No.

**Comment by weikengchen** [comment]
As CSRankings want to evaluate on raw data?

**Comment by emeryberger** [comment]
This is a non-starter. Different areas are generally not directly comparable. Weighting is not happening.

**Comment by weikengchen** [comment]
But today CSRanking by default show up a ranking that adds all areas directly together.
Many schools use this total ranking. 

In the README, there is:
"This approach is intended to be difficult to game, since publishing in such conferences is generally difficult"

Don't you think, in a higher level, if a school wants to get better CSRanking, 
Can the school decide not to hire anyone other than AI?

It is not comparable. Then why you by default add them all together, and,
" Prominent mentions of CSrankings: Berkeley | CMU (1, 2) | Cornell | Edinburgh | Michigan | Technion | UBC | UNC | Utah | Waterloo | Wisconsin | Yann LeCun | John Regehr | Charles Sutton "

thanks them! while some of them use "total ranking".

**Comment by weikengchen** [comment]
This issue is not a feature that starts "compare different areas".
But this issue is trying to stop "compare different areas".

**Comment by emeryberger** [comment]
All schools are on a level playing field with respect to all areas. Because counts across areas are combined by geometric mean, publication rates are implicitly normalized.

**Comment by weikengchen** [comment]
Found that in the FAQ.  It is a nice design!

I think it answers my question as I think this is not a weighted mean but has the similar advantage.

I am just not sure whether there will be a better way than geometric mean.

**Comment by fycus-tree** [comment]
@weikengchen see #562 for some more thoughts on this topic.

I tend to think of a geometric mean as a percentage mean. Say you have two depts, A and B. A publishes ~10% less papers in one area (9/10) and ~10% (10/9) more papers in another area, compared to dept B. A and B will have the same ranking. If you used arithmetic means, if the first area is 10x more "prolific" than the second, then dept A would be ranked much lower than B. So this ranking cares about how much more you publish per area, in terms of relative ratios. 

Now this makes some assumptions about the categorization of the areas you compute geometric means over. But there's enough of that from me in #562. For a quick example of some issues (I have) with the current system, look at how much the rankings change if you check/uncheck "Economics and computation" (a fairly small field). You'll see Berkeley go from being slightly behind Stanford, to being 10% above Stanford in the rankings (because Tim Roughgarden is at Stanford and Berkeley doesn't have people who publish in EC).

**Comment by weikengchen** [comment]
Then I have a question: does merging two fields or separating a field into two change the score dramatically?

**Comment by fycus-tree** [comment]
It depends on what you mean by dramatically. But yes, if EC got merged into theory, you'd a similar effect to turning EC off entirely.  This would change some scores by about 10%, which is a disproportionate ranking change compared to the size of that subfield as a whole. This highlights some of the implicit assumptions of using geometric means over fields instead of summation, which is some notion of equality or orthogonality across the subfields. 

Similarly, if a larger field got split into subfields where some universities don't publish in some of the  subfields, you could also see a decent size change in rankings (say.. robotics gets split into model-based & learning-based robotics. if some schools only focus on one, their rankings would drop compared to schools who have both, even if the total number of contributions is the same). 

As an alternative, simply summing all contributions across fields clearly would be invariant to any grouping operation.  Likewise, an arithmetic mean is a just a rescaled summation, so that would also be invariant. But then larger fields could swamp smaller fields. If you have some ideas for new metrics, I suggest doing that in #562 or perhaps a new issue with your proposal. 

EDIT: I believe the only mean invariant to grouping would be an arithmetic mean or a summation. Weighting fields based on size is one idea (log weights give a power law assumption) that would mitigate the giant score changes with grouping operations. But I think it needs a lot more thinking and some quantitative evaluation.
