### ISSUE TITLE
Law and policy should be added to the list of interdisciplinary fields

### ISSUE THREAD

**Issue by Susan-Landau** [emeryberger/CSrankings#839]
Cyberlaw and cyberpolicy are increasingly important, but are missing from the list of interdisciplinary fields. They don't quite fit the rubric of main conferences—publications are in many different law reviews and some policy journals (as well as books). Despite the complexity this creates, I'd urge adding this. Various schools are creating programs jointly between cs and law/policy. Adding the field will strengthen the list, as well as increase the viability of this important interdisciplinary area.

**Comment by fycus-tree** [comment]
I see two challenges with this proposal. The first is Emery's policy on the FAQ

>  For any research-focused area to be included, at least 50 R1 institutions must have publications in the top conferences in that area in the last 10 years. This threshold is to ensure that there is enough research activity in an area to enable a meaningful ranking. A number of ACM SIGs do not meet this criteria. 

The chat regarding medical imaging in #611 is a good example of the type of data that community should collect to demonstrate the good standing of a field. 

A second issue is that CSRankings uses [DBLP](https://dblp.uni-trier.de/) as their data source, which may not cover the publications you're recommending. This is a problem in computational biology as well, where Emery doesn't use the incomplete listings from [Nature](https://dblp.uni-trier.de/db/journals/nature/), and DBLP doesn't index [Science](https://dblp.uni-trier.de/db/journals/science/) at all; let alone many of the smaller, but still high impact journals in the natural sciences.

**Comment by marcniethammer** [comment]
Honestly, I think #611 is not a good example of what a community should collect. 

The reality is that there currently seems to be no transparent process of getting an area included. In the end, the decision not to include medical image analysis was based on an "editorial decision" by Emery disregarding all the quantitative data I collected (per his requests). This was and is extremely frustrating and (in my opinion) directly contradicts the goal of csrankings to measure things quantitatively.

**Comment by fycus-tree** [comment]
@marcniethammer I guess I'll have to disagree with you. I think you did an excellent job collecting quantitative measures for inclusion, including the 50 R1 criteria and looking at acceptance rates and publication numbers for that field. Proposals for new areas should include due diligence like that. 

The editorial decision, per #762, is somewhat orthogonal. I'm also eagerly awaiting a response to it. I think the core issue, applicable to many other areas, is how these sub-fields are created, and the current three conference maximum per sub-field. If there were 4 allowed conferences, I'm sure Emery would probably be fine adding MICCAI under computer vision. If we did an algorithmic creation of subfields, maybe MICCAI + IPMI would get a stand-alone field, be part of vision, or maybe excluded. But this is again the 3 conference thing and the SIG-based categories.

**Comment by marcniethammer** [comment]
@fycus-tree , you are right. I got a little carried away with my response, sorry. I wished there would be clear criteria that would need to be fulfilled for inclusion and I'd be happy to contribute drafting some if there would be a desire to do so. 

As it stands, I just find the situation very frustrating. Obviously, it would be better to move forward constructively. I think it would be great, for example, if there would be a board in charge of making decisions and formulating clear policies for inclusion, so that once due diligence has been done it would be clear and transparent why one area is included and another one is not.

As far as the three conference rule and the SIG-based categories are concerned this seems pretty arbitrary to me. Especially, as the SIG rule is not consistently applied and it is pretty unclear how the areas that are currently included (for example in the interdisciplinary sub category) have been chosen.

In my opinion, it should be about quality. And when in doubt I think it would be much more graceful to include areas rather than to exclude them (and with them entire CS communities).
