### ISSUE TITLE
CVPR 2018 papers are missing

### ISSUE THREAD

**Issue by rahmati** [emeryberger/CSrankings#919]
This is a dblp issue but worth mentioning as it is affecting the rankings. There seems to be a long lag between the conferences and dblp updates. CVPR 2018 has come and gone but the papers have not yet been listed.

**Comment by emeryberger** [comment]
Hi @rahmati - I do updates roughly every month. Why not more frequently? Because every update leads to manual labor for me because of DBLP changing author names (adding disambiguation entries); I then need to figure out which disambiguation entry now represents the relevant authors. Just for you, I will update DBLP and let you know how much work this entailed :).

(Also, I think you are probably overestimating how much one conference affects the rankings.)

**Comment by emeryberger** [comment]
One hour later, done. Next update in a month! (Note: as anticipated, no change in the top 48 schools for computer vision.)
